### ISSUE TITLE
コードのバージョンを最新版のみ残すように、ディレクトリ構成を修正

### ISSUE THREAD

**Issue by hasegawa-yuta-jaea** [shimomurakazuya/diff_eq#1]
@shimomurakazuya 

練習コードに関する議論はこちら（GitHubのIssueやPull Request）で行いましょう。
メールよりも議論の履歴を追跡しやすいのと、markdownが使えるので少し読みやすくなるメリットがあります。
また、 e79c707844fc12f70be0364a11e3b8f09afe2ee1 のように、コミット番号を貼るとそのままURLのリンクになってくれます。これも便利ですね。

---

それで、まずお願いですが、最新版のコードだけ残して使わないディレクトリを削除しましょう。
たぶん `diff1d_0519_fw12/2_class` が最新ですね？であれば、

``` bash
mv diff1d_0519_fw12/2_class src
rm -rv diff1d_0519 diff1d_0519_fw12
```

などとすれば良いかと思います。

**Comment by shimomurakazuya** [comment]
ディレクトリの構成を変更してみたのですが、うまく反映されません。

やったこととしてはローカルレポジトリ(git init済みのディレクトリ内)で
以下の操作を行いました

git clone https://github.com/shimomurakazuya/diff_eq.git

cd diff_eq
mv diff1d_0519_fw12/2_class src
rm -rv diff1d_0519 diff1d_0519_fw12
cd ../
 git push diff_eq master 


最後のコマンドを打った後、以下の文章が出てきました。ただgithubの方を確認すると変更が反映されていませんでした。
  Everything up-to-date

ローカルの変更をgithub上に反映させるのはgit push ではないのでしょうか？

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

pushの前にコミットを行う必要があります。

```bash
cd diff_eq
mv diff1d_0519_fw12/2_class src
rm -rv diff1d_0519 diff1d_0519_fw12
```

の後に

1. `git status` で変更内容を確認
2. `git add ほげほげ` でgitに反映させるファイルを指定。ディレクトリ内すべて反映するなら`git add .` でもOK。
3. `git commit -m 'コメント'` でコミット。コメントは変更内容が分かるように書く、シングルクオーテーションで囲う。
4. ここまでやって漸く`git push`

としてください。あと最後の`cd ..`がよく分かりません。必要ですか？

**Comment by shimomurakazuya** [comment]
構成を変更できました。ありがとうございます。

**Comment by shimomurakazuya** [comment]
課題３の間引きデータ出力に関しての実装が完了したのでコードを更新しました。1c29591

また、今コードのファイル分割を行い、コンパイルを行おうと思ったのですが以下のエラーが発生し実行ファイルが生成されません。
[a214026@s86fs2]~/diff/dif1d/3_files_shimomura% make
g++ -O3 -o run main.o -std=c++11 -lm -Wall -Wextra
main.o: 関数 `main' 内:
main.cpp:(.text.startup+0x21): `ValuesDiffusion::allocate_values()' に対する定義されていない参照です
main.cpp:(.text.startup+0x2b): `ValuesDiffusion::allocate_values()' に対する定義されていない参照です
main.cpp:(.text.startup+0x35): `ValuesDiffusion::init_values()' に対する定義されていない参照です
main.cpp:(.text.startup+0x3f): `ValuesDiffusion::init_values()' に対する定義されていない参照です
main.cpp:(.text.startup+0x56): `ValuesDiffusion::swap(ValuesDiffusion*, ValuesDiffusion*)' に対する定義されていない参照です
main.cpp:(.text.startup+0x65): `ValuesDiffusion::time_integrate(ValuesDiffusion const&)' に対する定義されていない参照です
main.cpp:(.text.startup+0x9c): `ValuesDiffusion::print_sum(int)' に対する定義されていない参照です
main.cpp:(.text.startup+0xc5): `Output::setout(ValuesDiffusion, int)' に対する定義されていない参照です
collect2: エラー: ld はステータス 1 で終了しました
make: *** [run] エラー 1

さらに長谷川さんが作成した元のコード（私の改変する前のコード）でもコンパイル時に同様のエラーが発生しました。
makefileの中身については特に変更は行っていません。(変える必要がないはず？)

原因は不明ですが取り急ぎ報告しておきます。

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

どうもありがとうございます。
ディレクトリ構成は確認しました。

課題3の件は別のIssueを立てるのでそちらで議論しましょう。
（基本的に1トピック1 issueが良いです。トピックの粒度は迷子になりがちですが。。）

---

Close #1 with a5228244c4ce60dbd85aca629d42c46ba3a44ddf
