### ISSUE TITLE
間引きデータ出力とmakefile

### ISSUE THREAD

**Issue by hasegawa-yuta-jaea** [shimomurakazuya/diff_eq#3]
課題３の間引きデータ出力に関しての実装が完了したのでコードを更新しました。[1c29591](https://github.com/shimomurakazuya/diff_eq/commit/1c29591286044e56886bce739ce355331bd6ac83)

また、今コードのファイル分割を行い、コンパイルを行おうと思ったのですが以下のエラーが発生し実行ファイルが生成されません。

```
[a214026@s86fs2]~/diff/dif1d/3_files_shimomura% make
g++ -O3 -o run main.o -std=c++11 -lm -Wall -Wextra
main.o: 関数 `main' 内:
main.cpp:(.text.startup+0x21): `ValuesDiffusion::allocate_values()' に対する定義されていない参照です
main.cpp:(.text.startup+0x2b): `ValuesDiffusion::allocate_values()' に対する定義されていない参照です
main.cpp:(.text.startup+0x35): `ValuesDiffusion::init_values()' に対する定義されていない参照です
main.cpp:(.text.startup+0x3f): `ValuesDiffusion::init_values()' に対する定義されていない参照です
main.cpp:(.text.startup+0x56): `ValuesDiffusion::swap(ValuesDiffusion*, ValuesDiffusion*)' に対する定義されていない参照です
main.cpp:(.text.startup+0x65): `ValuesDiffusion::time_integrate(ValuesDiffusion const&)' に対する定義されていない参照です
main.cpp:(.text.startup+0x9c): `ValuesDiffusion::print_sum(int)' に対する定義されていない参照です
main.cpp:(.text.startup+0xc5): `Output::setout(ValuesDiffusion, int)' に対する定義されていない参照です
collect2: エラー: ld はステータス 1 で終了しました
make: *** [run] エラー 1
```

さらに長谷川さんが作成した元のコード（私の改変する前のコード）でもコンパイル時に同様のエラーが発生しました。
makefileの中身については特に変更は行っていません。(変える必要がないはず？)

原因は不明ですが取り急ぎ報告しておきます。

_Originally posted by @shimomurakazuya in https://github.com/shimomurakazuya/diff_eq/issues/1#issuecomment-844753934_

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

先にmakefileの件にコメントしておきますと、
ファイルを分割した時点でmakefileの変更は必要になります。

makeのすぐ下のコマンドが
```bash
g++ -O3 -o run main.o -std=c++11 -lm -Wall -Wextra
```
となっていますが、これが
```bash
g++ -O3 -o run main.o ValueDiffusion.o -std=c++11 -lm -Wall -Wextra
```
などとなるように`makefile`を修正する必要があります。

元の（私の作ったほうの）`3_files` の `makefile`を参照してください。
（まあこれもあまり良くない書き方なのですが。。とりあえずはエラーは回避できるかと思います）

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

次にgitとGitHubの使い方ですが、

1: 

GitHubのIssue（このページ）はMarkdown対応ですので、Markdownで見やすいように書いてください。（といってもこだわりすぎても時間の無駄になりますが。。）
最小限の対応としては、以下のように、

\`\`\`
コードやターミナルの出力などはチルダ3個で括る
\`\`\`

としてくれると助かります。これだけでも見やすさがかなり違います。

2: 

Gitにはmakeに最小限必要なコードのみを入れるべきで、`main.o`, `run`（`make`で生成されるファイル）などは不要です。
それで、gitの作法として、これらの不要なファイルを無視するために`.gitignore`を作成する必要があります。下記に例を置いておきます。
```.gitignore
# .gitignore
*.o
run
```
`main.cpp_bu`なども、同様の理由でGitに入れるべきではないです。計算結果 `png/` を入れるかは、議論が分かれるところですが、ファイルサイズが大きくなるようなら（だいたいMByteを超えるようなら）、入れるべきではないです。

3:

2に関連しますが、Gitに入れるべきでなくて既に入ってしまっているものは、
```
git rm *.o
```
などとしてGitから削除してください。

4:

これはgit というかコードの話かもしれませんが、

- 使わなくなった行はコメントアウトではなく、できれば削除してください。あまりコメントアウトが多いとコードが読みづらくなります。（といってもCityLBMもコメントアウトだらけなのですが。。そのうち整理しないと。。。）

- まだインデントが整ってないように思います。`.vimrc`に、以下を追記して貰えますか？
```
" ~/.vimrc
set nocompatible
set encoding=utf-8

" tab
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=0

set cindent
set smartindent
filetype plugin indent on

" display
set number
set ruler
```

**Comment by shimomurakazuya** [comment]
長谷川さん、
ファイル分割したコードを上げましたので確認お願いします。
コミット番号は944df28です。

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

まだ`makefile~merged`, `run`といった不要なファイルが残っていますので、以下の対応をしていただけますか？

> 2:
> 
> Gitにはmakeに最小限必要なコードのみを入れるべきで、main.o, run（makeで生成されるファイル）などは不要です。
> それで、gitの作法として、これらの不要なファイルを無視するために.gitignoreを作成する必要があります。下記に例を置いておきます。
>
> ```
> # .gitignore
> *.o
> run
> ```
> main.cpp_buなども、同様の理由でGitに入れるべきではないです。計算結果 png/ を入れるかは、議論が分かれるところですが、ファイルサイズが大きくなるようなら（だいたいMByteを超えるようなら）、入れるべきではないです。
> 
> 3:
> 
> 2に関連しますが、Gitに入れるべきでなくて既に入ってしまっているものは、
> 
> git rm *.o
> などとしてGitから削除してください。

コードはこのあと読むので、しばらくお待ちください。
（このあと、と言いつつ今日中の返事は間に合わないかもしれませんが。。）

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

読みました。コードレビューのコメントです。このコミットで直してくれても良いですし2次元拡散方程式と並行して直しても良いです、判断はまかせます。

なお、以下、チェックボックスになっているので、直ったものから順にチェックを付けてみてください。

- `Output.h`について（`Output.cpp`の関連する部分も直してください）
  - [ ] `float *x__;` `ValuesDiffusion* v__;` などは使わないですよね？使わない変数は削除しましょう。
  - [ ] CityLBM的には`float` ではなく `real` です。（私の書いたバージョンから間違えていました。すみませんが修正してください）
  - [ ] `average()`, `maximum()` の引数に `f_ave` は不要です。関数スコープの頭で同名のローカル変数を定義すれば良いです。
  - [ ] `setout()`, `average()`, `maximum`の引数の型、`ValuesDiffusion` → `const ValuesDiffusion&` に修正してください。なお、補足すると、
    * `const` は変更しない変数につける修飾詞です。
    * `&` は参照型です。もしくは、計算科学でいうところのshallow copyです。逆に`&`を付けないものは値渡し（またはdeep copy）と呼ばれますが、メモリを無駄喰いするので非推奨です。 
  - [ ] `setout()` の関数名の由来がよくわかりません。set output ですか？
    * CityLBMに忖度するなら関数名は`OutputDiffusionData()` とかですかね。

- `Output.cpp`について
  - [ ] まだ全体的にインデントが整っていません。どこかのタイミングで直してください（なるべく早い方が良い）
  - [ ] `setout()` でファイル出力名が`t=0000.dat`などになっていますが、イコール記号は良くない気がします。
    * これもCityLBMに忖度するなら、`ascii_value_stepほげほげ.dat` とかですかね。
  - [ ] `setout()`の44行目、`if(i% defines::downsize == 0)`のif文は要らないですね？43行目のforとくっつけて
    ```
    for(int i=0; i<defines::nx; i += defines::downsize)
    ```
    とした方がコードがすっきりするかと思います。
  - [ ] `average()`, `maximum()`は、`Output.h`と同様に修正してください。

- `ValuesDiffusion.h, .cpp`について
  - [ ] `print_sum()` ですが、こっちよりも`Output`クラスがふさわしい気がしますね。関数丸ごと移動させておいてください。

- その他
  - [ ] Gitについては1つ上のコメントに対応してください。
  - [ ] makeで警告が大量に出てきますが、これが出なくなるようにコードを修正してください。
  - [ ] `makefile`は、このままだと良くないのですね（.cpp ファイルが増えるたびに`makefile`を書き換えるのは良くない）
    といっても`makefile`なんて本質ではないので、こちらでさくっとサンプルを作りました。差し替えておいてください。
    ```makefile
    # makefile
    CXXFLAGS += -std=c++11 -O3 -Wall -Wextra
    LDFLAGS += -std=c++11 -lm -Wall -Wextra

    .PHONY: all clean resultclean tagfiles

    TARGET := run

    SRCS := $(wildcard *.cpp)
    OBJS := $(SRCS:.cpp=.o)

    all: $(TARGET)
	
    $(TARGET): $(OBJS)
    	g++ -O3 -o $@ $^ $(LDFLAGS)

    .cpp.o:
    	g++ -O3 -c $< $(CXXFLAGS)

    clean:
    	rm -f $(TARGET)
    	rm -f $(OBJS)

    retultclean:
    	find -name data/ '*.dat' | xargs rm -f 

    tagfiles:
    	ctags -R --langmap=c:+.hpp .
    ```
    (5/24追記) makefileの`tagfiles`のところを間違えていたので修正しました。

とりあえず以上です。わからないものがあれば聞いてください。

**Comment by shimomurakazuya** [comment]
インデントに関してはfor,if文が入るたびにtabキーでインデントを深くしていく形にしていますがそれでよろしいでしょうか？

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

よくないですね。手動で頑張っても失敗しか生まないので、なるべく自動化しましょう。

vimなら`.vimrc`に以下を追記してください。

```
" ~/.vimrc

" configure tab and indent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=0
set cindent
set smartindent
filetype plugin indent on
```

**Comment by shimomurakazuya** [comment]
これ入れてあれば、すでに記述されている分もenterキー押すだけで綺麗になりますか？

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

はい。`cindent`とか`smartindent`とかがいい感じに整えてくれますので、とりあえずはそれに従ってインデントすれば良いです。

**Comment by shimomurakazuya** [comment]
また、先ほどの会議で二次元方程式のコードのコンパイルが通らないと言っていましたが、具体的には
以下のエラー文が出ています。
index.cpp内にあるnamespace内の関数を参照して欲しいのですが、それを行ってくれないようです。
namespaceからの関数の呼び出しは実体化の宣言しないといけませんでしたっけ？

取り急ぎ、gitのソースコードを更新しました。

コミット番号　
559c8a04f58d807155082abaa920e5a3cc7c7dfb

'''
[a214026@s86fs2]~/diff/dif2d% make
g++ -O3 -c Output.cpp -std=c++11 -O3 -Wall -Wextra
In file included from ValuesDiffusion.h:5:0,
                 from Output.cpp:9:
Index.h:6:9: 警告: inline function ‘int index::index_xy(int, int)’ used but never defined [デフォルトで有効]
     int index_xy(int i, int j);
         ^
g++ -O3 -o run ValuesDiffusion.o Output.o Index.o main.o -std=c++11 -lm -Wall -Wextra
Output.o: 関数 `Output::OutputDiffusionData(ValuesDiffusion const&, int)' 内:
Output.cpp:(.text+0x58c): `index::index_xy(int, int)' に対する定義されていない参照です
Output.cpp:(.text+0xc85): `index::index_xy(int, int)' に対する定義されていない参照です
ValuesDiffusion.o: 関数 `ValuesDiffusion::init_values()' 内:
ValuesDiffusion.cpp:(.text+0xe9): `index::index_xy(int, int)' に対する定義されていない参照です
ValuesDiffusion.o: 関数 `ValuesDiffusion::time_integrate(ValuesDiffusion const&)' 内:
ValuesDiffusion.cpp:(.text+0x1d4): `index::index_xy(int, int)' に対する定義されていない参照です
collect2: エラー: ld はステータス 1 で終了しました
make: *** [run] エラー 1
'''

**Comment by shimomurakazuya** [comment]
上のコメントはisuueから外れてるのでまた新しくissue立てます。

**Comment by hasegawa-yuta-jaea** [comment]
よく考えたらこのissueのタイトルはファイル間引き出力なので、既に完了していますね。。
コードレビューは別件な気がしてきたので移動させます。
