### ISSUE TITLE
コードの精度検証

### ISSUE THREAD

**Issue by shimomurakazuya** [shimomurakazuya/diff_eq#7]
技術的な話ですが、SGI上でpngファイルって閲覧できますか？

**Comment by hasegawa-yuta-jaea** [comment]
やり方はいろいろありますが出来ます。

- VNC接続する？
  → 私は方法を知らないので、杉原さんあたりに聞いてください

- `JupyterLab`を使う。
  → これは申請が必要。というかJupyterLabはわかりますか？ 1から始めるとなると結構大変ですが。。

- Xつきでsshログインして `eog` コマンドを叩く
  → ユーザとしてはこれが一番簡単なんですが、問題として、SGI8600に eog がインストールされていないことがあります。（インストール依頼しないといけない。やってくれる望みは薄い）

どれでもいいですが好きな方法でやってください。JupyterLab なら教えられます。

どれもめんどくさそうでやりたくない、とかなら、諦めて scp でもいいです。

**Comment by shimomurakazuya** [comment]
精度検証についてですが、まず一次元コードで格子間隔毎の数値、及び解析会の誤差を調べました。
しかしながら、表の通り誤差がdx^2に比例してはいませんでした。

t=1
![image](https://user-images.githubusercontent.com/82013395/119788980-95954580-bf0d-11eb-8bdb-9a11cd4c727e.png)

t=5
![image](https://user-images.githubusercontent.com/82013395/119789139-c2e1f380-bf0d-11eb-8ab0-9fdf3442c55c.png)


おそらく時間発展のeuler法の誤差が影響していると考えられますが、誤差が収束するのかどうかを次に調べようと思います。

**Comment by shimomurakazuya** [comment]
こちらが表の誤差をグラフ化したものです。

![image](https://user-images.githubusercontent.com/82013395/119789410-ff155400-bf0d-11eb-8b96-d58d4f8722b4.png)

**Comment by hasegawa-yuta-jaea** [comment]
誤差の取り方が問題な場合もあります。

とりあえず下記が問題ないか確認してください。
（といっても、私ももう昔のことなので何が正しいのか覚えてないですが。。）

- これはL2ノルムですか？もしくは各格子点のエラーの総和ですか？

- `t`はなんですか？ step数？ step ×  `dt`？

- 解像度変えた時の時間刻みはどうなっていますか？ `dt`一定？ CFL一定？

- あと、グラフは両対数にしてください。欲を言うと`dx^2`の傾きの補助線もつけて欲しいです。

**Comment by shimomurakazuya** [comment]
わかりました。

・L2ノルムではないです。関数の最大値と解析回との誤差をとっただけです。

・tは step × dt

・解像度についてはdt一定です。

・両対数了解しました。

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

了解です。

errorとtの定義は大丈夫そうな感じがありますね。

>・解像度についてはdt一定です。

dtじゃなくてCFL一定だったような。。。

それで昨日渡したPDF読んでみたら

- 時間刻みは Δt = 0.25 * Δx^2 / κ で指定 している

とありました。
これやれば2次精度になるのですね？たぶん？？

**Comment by shimomurakazuya** [comment]
資料の通りで計算が正しければそうなると思いますので、時間刻み幅もそれに倣ってみます。

一次元コードでの精度検証用にL1エルムの計算関数を追加したのですが、あげた方がいいですよね？
その場合今上げているsrcディレクトリとは別に挙げた方がいいですか？

**Comment by hasegawa-yuta-jaea** [comment]
> 一次元コードでの精度検証用にL1エルムの計算関数を追加したのですが、あげた方がいいですよね？

L1書いたのならそっちの方が良いので上げていただけると良いです。

**Comment by shimomurakazuya** [comment]
エルム計算関数追加版別ディレクトリで上げました。
c78d31cc8fe2f37088580b28981b5939b9aa4f95

Output.cppに関数名analytic（後で変えます）で計算しています。また、defineのdtの定義式を Δt = 0.25 * Δx^2 / κ としました。

**Comment by hasegawa-yuta-jaea** [comment]
別ディレクトリは良くないです。git で履歴を追跡出来なくなります。

どうしても両方残したければ、

- gitのブランチを切る
- `#ifdef` などで切り替えられるようにする。
- いっそ両方出力する

などしてください。

**Comment by shimomurakazuya** [comment]
取り急ぎ現在の進捗についてまとめも兼ねて報告します。

精度検証についてですが、難航しています。
解析解と数値解との比較を行なっているのですが、合致していません。

![image](https://user-images.githubusercontent.com/82013395/119942925-54fd0100-bfcd-11eb-92db-0a2720783088.png)

> 上図は書く時間ごとの解析解と数値解とのL1エルムを示しています。重なっていますが格子点ごとのグラフはnx=50,100,200の三本あり、格子点にかかわらずほぼ同じ振る舞いをしており、格子間隔dxの二乗に比例する形でないのは明らかです。

この誤差は、いずれも最終的に単精度の丸め誤差程度で収束します。

ここからは仮説ですが、
この差異の原因は数値解と解析解の減衰値(expの肩の値)が違うためであると考えています。
t=0においてはいずれの場合も誤差は０であることは確認しているためです。

なのでこれから減衰の仕方が異なる原因を探っていくつもりです。

**Comment by hasegawa-yuta-jaea** [comment]
コードはちょっとしか読めていないのであれですが、

- L1 ノルム は総和ではなく絶対値の総和です。
- normalize が抜けている気がします。
  `Σ|f - f_true|` ではなく `Σ|f - f_true| / Σ|f|` ですが、そのようになっていますでしょうか？

**Comment by shimomurakazuya** [comment]
絶対値については付けています。（githubにコードをあげ忘れていました。すみません）

ただ、規格化については長谷川さんお通りにはなっていないので、これを反映してもう一度調べてみます。

**Comment by shimomurakazuya** [comment]
今朝のミーティングで相談した誤差の問題について、ここでもまとめます。f533e3ed908954cef6d094c0f521259d423de2c5

図は誤差のL1エルム(Σ|f - f_true| / Σ|f| / N)(Nは格子点数)の時間発展及び、格子間隔ごとの比較です。

各格子点数ごとの時間発展
![image](https://user-images.githubusercontent.com/82013395/120125272-07fa7400-c1f3-11eb-8315-1df3559adc79.png)

まず上図は数値解と解析解との誤差の時間発展を各格子点ごとに片対数でグラフ化したものです。いずれのグラフも時間発展とともに誤差は小さくなり、N=50,200,800はある数値で収束します(float定義による丸め誤差)。ただN=100,400はずっと小さくなり続けていました。ただ、今はあまりこの振る舞いの違いは関係ないとして無視しています。

次に、丸め誤差で収束する前の誤差は格子間隔に比例する関係にあると考え、t=0.1での誤差の大きさを調べました。それが下の図です。

t=0.1での各格子点数ごとの誤差の大きさ
![image](https://user-images.githubusercontent.com/82013395/120125279-0df05500-c1f3-11eb-960e-ed404100effc.png)

こちらは両対数グラフで補助線としてdx^2の線を引きました。で、N<200まではdx-2に概ね沿うかたちになっている一方で（それでも直線ではないですが）N=>400からは誤差が増大しています。

現在この原因を調査しています。

**Comment by shimomurakazuya** [comment]
長谷川さん、誤差評価について完全に手詰まりなので、zoomで相談したいのですが、よろしいでしょうか？

**Comment by hasegawa-yuta-jaea** [comment]
すみません、良く分かりませんがGitHubの通知が来なくなっていたようですね。

@hasegawa-yuta-jaea 

のように @ をつけてもらったほうが確実に通知が来るので、つけていただけると助かります。

**Comment by shimomurakazuya** [comment]
![image](https://user-images.githubusercontent.com/82013395/120149898-51fc4d80-c225-11eb-881f-f47e8fd9757b.png)

**Comment by shimomurakazuya** [comment]
@hasegawa-yuta-jaea
長谷川さんへ、倍精度にしたら誤差が、dx^2に比例するようになりました。

![image](https://user-images.githubusercontent.com/82013395/120155290-9db1f580-c22b-11eb-9a74-0e8b2181348b.png)

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

そうですか。よかったですね。
（境界条件の話は、関係なかったですね。良くわからないで適当なこと言ってすみませんでした）

2日間ご苦労様でした。

**Comment by shimomurakazuya** [comment]
@hasegawa-yuta-jaea 
ミ~ティングで言っていた検証用コードです。このコードのレビューをお願いします。
dca331c85402574bd7f4332701dd0743cead7eb1

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

ありがとうございます。このあと読みます。

コードレビューの件は別の issue ( #8 ) に書く予定ですので、この issue は閉じていただいて結構です。
