### ISSUE TITLE
コードレビュー(2)

### ISSUE THREAD

**Issue by hasegawa-yuta-jaea** [shimomurakazuya/diff_eq#8]
@hasegawa-yuta-jaea 
ミ~ティングで言っていた検証用コードです。このコードのレビューをお願いします。
dca331c85402574bd7f4332701dd0743cead7eb1

_Originally posted by @shimomurakazuya in https://github.com/shimomurakazuya/diff_eq/issues/7#issuecomment-851750245_

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

すみません、書き直しになってしまってモチベが低いので、かなりはしょっています。。。分かりにくい部分があれば遠慮なく聞いてください。

1次元コードの頃に比べるとだいぶ良くなっていると思います。修正コメントは以下4つです。（1次元の時はコメント13個だったのでだいぶ改善しましたね。。）

- [x] 再びインデントが崩れています。（特に `Output.cpp` の `OutputDiffusionData()` とか `analytic()` とかがひどい）
  なんだろう、Vimのsmartindentが効いていないのでしょうか。。とりあえず、ファイル内の全インデント一括修正（下記コマンド）を試してみてください。

  - Vimでファイルを開いて、`gg` → `Shift+v` → `Shift+g` → `=` 

  これで直らなかったらお知らせください。ちょっと対策を考えます。

- [x] 口頭でも伝えましたが、`j + ny*i`→`i + nx*j`、`for(j) { for (i) { ... }}`の順序に修正お願いします。（C++言語、CityLBMの仕様に合わせるため。修正多めですが、すみません、ご対応ください。）
       （15:55修正: forの順序を書き間違えていたので修正しました）

- [x] `Output.h`の`f_ave__`は使ってなさそうだったので削除してください。

- [x] `ValuesDiffusion.h`の`index_xy()`も使ってなさそうだったので削除してください。`index::index_xy()`と`ValuesDiffusion::index_xy()`が居て紛らわしいです。

**Comment by shimomurakazuya** [comment]
@hasegawa-yuta-jaea 
とりあえず。指摘された部分は修正しました。インデント一括整理コマンドも正常に動きました。こちらのコードは後ほどあげておきます

後、円周率piについての扱いなのですが、自分でdefines.hにpi=M_PIとするのかM_PIをベタ書きするのか、city_LBMではどちらなのですか？

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

どうもありがとうございます。

> 後�、円周率piについての扱いなのですが、自分でdefines.hにpi=M_PIとするのかM_PIをベタ書きするのか、city_LBMではどちらなのですか？

vimgrepしたら `M_PI` が出てきたので、ベタ書きで良いかと思います。

```vim
initialize_srcs/InitTaylorGreen.h|32 col 40|  double k0()     const { return 2.0*M_PI/L0(); }
```

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

すみませんひとつ忘れていました。
打ち合わせで出ていた件ですが、

- [x] 2次元インデックスで、周期境界条件を剰余演算で記述

の方法は分かりましたか？

**Comment by shimomurakazuya** [comment]
@hasegawa-yuta-jaea 
d74eefd7e73dc3477a753d81a30dd8bdeeaf7278
そちらに関しても反映したものを上げました。一応こちらでも該当箇所を記載します。
i,jそれぞれで剰余計算したのちにijを計算する方法をとっています。

```
void ValuesDiffusion::
 41 time_integrate(const ValuesDiffusion& valuesDiffusion) {
 42     real* fn = f_;
 43     const real* f = valuesDiffusion.f_;
 44     for(int j=0; j<defines::ny; j++) {
 45             const int jm = (j-1 + defines::ny) % defines::ny;
 46             const int jp = (j+1 + defines::ny) % defines::ny;
 47         for(int i=0; i<defines::nx; i++) {
 48             const int im = (i-1 + defines::nx) % defines::nx;
 49             const int ip = (i+1 + defines::nx) % defines::nx;
 50             
 51             const int ji = index::index_xy(i,j); 
 52             const int jim = index::index_xy(im,j);
 53             const int jip = index::index_xy(ip,j);
 54             const int jim2 = index::index_xy(i,jm);
 55             const int jip2 = index::index_xy(i,jp);
 56             
 57             fn[ji] = f[ji] + 
 58                 + defines::c_dif * defines::dt / defines::dx / defines::dx * (f[jim] - 2*f[ji] + f[jip] )
 59                 + defines::c_dif * defines::dt / defines::dx / defines::dx * (f[jim2] - 2*f[ji] + f[jip2]);
 60         }       
 61     }           
 62 }       

```

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

ありがとうございます。

> i,jそれぞれで剰余計算したのちにijを計算する方法をとっています。

そうです。それで合っています。

あとは、念のため最新バージョン ( d74eefd7e73dc3477a753d81a30dd8bdeeaf7278 ) で2次精度が出るか確認して、問題なければこの issue と #4 を close ですかね。

この issue を閉じたら続きは #6 でやりましょう。

**Comment by shimomurakazuya** [comment]
誤差評価しましたが、問題はなかったです。コード書き換える前の誤差の数値と全く同じでした。

![image](https://user-images.githubusercontent.com/82013395/120405707-293e9a00-c384-11eb-8d70-c85808e79d2f.png)

**Comment by hasegawa-yuta-jaea** [comment]
@shimomurakazuya 

確認ありがとうございます。これで安心して次に進めますね。
このissue は閉じていただいて結構です。
